{% set version = "1.1.9" %}

package:
    name: tuiview
    version: {{ version }}

source:
    fn: TuiView-{{ version }}.tar.gz
    url: https://bitbucket.org/chchrsc/tuiview/downloads/TuiView-{{ version }}.tar.gz
    md5: 7d0fd3a03ebbe5bd6a2fd5e49f5b70ba

build:
    number: 2
    entry_points:
        - tuiview = tuiview.viewerapplication:run
        - tuiviewwritetable = tuiview.writetableapplication:run

requirements:
    build:
        - python
        - numpy x.x
        - gdal 2.1.*
        - pyqt 4.11.*
    run:
        - python
        - numpy x.x
        - gdal 2.1.*
        - pyqt 4.11.*

test:
    imports:
        - tuiview

about:
    home: http://tuiview.org/
    license: GPLv2
    summary: Simple raster viewer. Supports Geolinked Windows, Raster Attribute Querying and Editing and Geographic Selection, Vector Overlay, Flicker, Profile Tool. 

extra:
    recipe-maintainers:
        - gillins
        - danclewley
