{% set version = "1.1.9" %}

package:
    name: tuiview
    version: {{ version }}

source:
    fn: TuiView-{{ version }}.tar.gz
    url: https://bitbucket.org/chchrsc/tuiview/downloads/TuiView-{{ version }}.tar.gz
    md5: 7d0fd3a03ebbe5bd6a2fd5e49f5b70ba

build:
    number: 1
    # PyQt not available for py35 yet
    skip: True  # [win and py35]
    entry_points:
        - tuiview = tuiview.viewerapplication:run
        - tuiviewwritetable = tuiview.writetableapplication:run

requirements:
    build:
        - python
        - numpy x.x
        - gdal 2.1.*  # [unix]
        - gdal 2.0.2  # [win]
        - pyqt
    run:
        - python
        - numpy x.x
        - gdal 2.1.*  # [unix]
        - gdal 2.0.2  # [win]
        - pyqt

test:
    imports:
        - tuiview

about:
    home: http://tuiview.org/
    license: GPLv2
    summary: Simple raster viewer. Supports Geolinked Windows, Raster Attribute Querying and Editing and Geographic Selection, Vector Overlay, Flicker, Profile Tool. 

extra:
    recipe-maintainers:
        - gillins
        - danclewley
