travis:
  secure:
    BINSTAR_TOKEN: lFRTnKG8pyOr+x4DqRjjJhXzk5oIIAxugNHcdWGmt1/h4isDReRQn4zPscaTiGkv6UERamBvwMf2b3+iBf/e/T+ghSY122GCG1sK4xYKYiLupaB8CSR2EJEwPDLO7yi2jehE8k6g+A4m8eQQ2bzO78cu5bWVdSLIOhfSka2OUIVzorshLBiMgFz3Yr/HynYJ5aiqyL3Tq2jI51fTrsdDR0XyUHHxw2XoT223gXEj54HyIIHDYE+fOTVddUqlunD9UURcTkXvrFJ3wjOivj+wK5CJ2AL/pFCVrjD0g6zf9VqyIQEWvw5KIAB/1zZX+eT+s9CoexOcdxC/Ehwpfejp/yZdxqea1UV7dD+f5C0JrIR7f6b5X/PPEsULB4AbptYHwfMbtelPjOvX+iM8GYGLd/VzMwNrz66BtCkOa3SHxwkj14w2nvyzWgGdJehgNsA1q/JNXikHMQwEyQ+8kA6X69EVNp9VQ6pVOFei+cLJj5OiyyOLGvZVSWg9LFfS5s8rC/5wsXEOPUrVj5nruz2V12kY4Q8YYosZJseE9BfwjO9OtWy6VLzF8FnaJoAzaPVNlbSOF8jksV2FP4P6wPMDRWbbkN5or/D15/FWBwYb7MWKROB1IvHVochSovdkPlS38DePtI2Qe8XJedEM725rlGBbk0RNRiebjmiMo3eAVrk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
